language: c
compiler: gcc

script: make tests rosettacode

addons:
  apt:
    packages:
        - gcc-multilib
        - linux-libc-dev:i386

sudo: false
git:
  depth: 1
branches:
  only:
    - master
