language: c
compiler:
  - gcc
  - clang
os:
  - osx


script: make describe tests rosettacode

addons:
  apt:
    packages:
      - gcc-multilib
      - linux-libc-dev:i386


sudo: false
git:
  depth: 1
branches:
  only:
    - apple
