name: build ol

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-18.04, ubuntu-16.04, macos-10.15, macos-11.0 ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build with CI build script
      run: 'make describe tests rosettacode'

  win-build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install MinGW toolchain
      run: sudo apt-get install gcc-mingw-w64-x86-64 mingw-w64-x86-64-dev

    - name: Build with CI build script
      run: 'make ol64.exe'
