name: build ol

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build with CI build script
      run: 'PATH=$PATH:$ANDROID_SDK_ROOT/ndk-bundle make describe android tests rosettacode'
